"""Constants for internal agents system."""

# Proposal generation
MIN_TOKEN_LENGTH = 4
DEFAULT_TOKEN_LENGTH = 5
TOKEN_LENGTH_MULTIPLIER = 10
MAX_TOKEN_LENGTH = 12

# Archivist agent
ARCHIVIST_RECENT_EPISODES = 20
ARCHIVIST_MUTATION_RATE_BASE = 0.1
ARCHIVIST_MUTATION_RATE_MULTIPLIER = 0.2
ARCHIVIST_CONFIDENCE_BASE = 0.7
ARCHIVIST_CONFIDENCE_STABILITY_MULTIPLIER = 0.2

# Weaver agent
WEAVER_FALLBACK_RECENT_EPISODES = 5
WEAVER_FALLBACK_MAX_TOKENS = 8
WEAVER_FALLBACK_CONFIDENCE = 0.4
WEAVER_COHESION_THRESHOLD = 0.6
WEAVER_TEMPERATURE_BASE = 1.5
WEAVER_TEMPERATURE_COHESION_MULTIPLIER = 0.5
WEAVER_CONFIDENCE_BASE = 0.6
WEAVER_CONFIDENCE_COHESION_MULTIPLIER = 0.3
WEAVER_TEMPLATE_CHANCE = 0.5

# Gardener agent
GARDENER_CLUSTER_DEPTH = 2
GARDENER_CLUSTER_TOP_K = 10
GARDENER_MIN_CLUSTER_SIZE = 2
GARDENER_MAX_TOKENS = 8
GARDENER_TEMPLATE_CHANCE = 0.5
GARDENER_MIN_TOKENS_FOR_TEMPLATE = 3
GARDENER_FALLBACK_RECENT_EPISODES = 5
GARDENER_FALLBACK_TOKENS_PER_EPISODE = 2
GARDENER_FALLBACK_MIN_TOKENS = 4
GARDENER_TEMPLATE_CHANCE_FALLBACK = 0.6
GARDENER_CONFIDENCE_BASE = 0.5
GARDENER_CONFIDENCE_COHESION_MULTIPLIER = 0.4

# Trickster agent
TRICKSTER_LENGTH_BASE = 3
TRICKSTER_LENGTH_MULTIPLIER = 5
TRICKSTER_TEMPERATURE = 2.5
TRICKSTER_RANDOM_WORD_CHANCE = 0.3
TRICKSTER_CONFIDENCE_BASE = 0.3
TRICKSTER_CONFIDENCE_NOVELTY_MULTIPLIER = 0.4

# Cartographer agent
CARTOGRAPHER_NEIGHBOR_COUNT = 3
CARTOGRAPHER_RECENT_EPISODES = 3
CARTOGRAPHER_TOKENS_PER_EPISODE = 2
CARTOGRAPHER_MIN_TOKENS = 6
CARTOGRAPHER_MAX_TOKENS = 8
CARTOGRAPHER_CONFIDENCE_BASE = 0.6
CARTOGRAPHER_CONFIDENCE_COHESION_MULTIPLIER = 0.3
CARTOGRAPHER_FALLBACK_SAMPLE_SIZE = 5

# Coordinator agent
COORDINATOR_DRIVE_ALIGNMENT_BASE = 0.5
COORDINATOR_DRIVE_ALIGNMENT_MULTIPLIER = 0.5
