"""Constants for culture system."""

# Culture defaults
DEFAULT_COLLECTIVISM = 0.5
DEFAULT_OBEDIENCE = 0.5
DEFAULT_AGGRESSION = 0.5
DEFAULT_RISK_TOLERANCE = 0.5

# Culture initialization ranges
INITIAL_COLLECTIVISM_MIN = 0.2
INITIAL_COLLECTIVISM_MAX = 0.8
INITIAL_OBEDIENCE_MIN = 0.2
INITIAL_OBEDIENCE_MAX = 0.8
INITIAL_AGGRESSION_MIN = 0.2
INITIAL_AGGRESSION_MAX = 0.8
INITIAL_RISK_TOLERANCE_MIN = 0.2
INITIAL_RISK_TOLERANCE_MAX = 0.8

# Culture drift
DEFAULT_CULTURE_DRIFT_RATE = 0.005

# Escalation speed modifiers
ESCALATION_AGGRESSION_FACTOR_MULTIPLIER = 0.4
ESCALATION_OBEDIENCE_FACTOR_MULTIPLIER = 0.3
ESCALATION_BASE_FACTOR = 1.0

# Cooperation likelihood modifiers
COOPERATION_COLLECTIVISM_FACTOR_MULTIPLIER = 0.4
COOPERATION_AGGRESSION_FACTOR_MULTIPLIER = 0.3
COOPERATION_BASE_FACTOR = 1.0

# Violence likelihood modifiers
VIOLENCE_AGGRESSION_FACTOR_MULTIPLIER = 0.5
VIOLENCE_OBEDIENCE_FACTOR_MULTIPLIER = 0.4
VIOLENCE_BASE_FACTOR = 1.0

# Stress reaction thresholds
HIGH_OBEDIENCE_THRESHOLD = 0.7
HIGH_AGGRESSION_THRESHOLD = 0.7
HIGH_COLLECTIVISM_THRESHOLD = 0.7

# Stress reaction modifiers - Quiet Suffering (high obedience)
QUIET_SUFFERING_VIOLENCE_MOD = 0.6
QUIET_SUFFERING_MIGRATION_MOD = 0.5
QUIET_SUFFERING_COOPERATION_MOD = 0.8

# Stress reaction modifiers - Riots (high aggression)
RIOTS_VIOLENCE_MOD = 1.5
RIOTS_MIGRATION_MOD = 1.3
RIOTS_COOPERATION_MOD = 0.7

# Stress reaction modifiers - Mutual Aid (high collectivism)
MUTUAL_AID_VIOLENCE_MOD = 0.7
MUTUAL_AID_MIGRATION_MOD = 0.8
MUTUAL_AID_COOPERATION_MOD = 1.4

# Balanced reaction modifiers
BALANCED_VIOLENCE_MOD = 1.0
BALANCED_MIGRATION_MOD = 1.0
BALANCED_COOPERATION_MOD = 1.0

# Event evolution rates
VIOLENCE_AGGRESSION_INCREASE = 0.1
VIOLENCE_OBEDIENCE_DECREASE = 0.05
COOPERATION_COLLECTIVISM_INCREASE = 0.1
COOPERATION_AGGRESSION_DECREASE = 0.05
AUTHORITY_OBEDIENCE_INCREASE = 0.1
