"""Constants for intent system."""

# Intent defaults
DEFAULT_SURVIVE = 0.5
DEFAULT_EXPLORE = 0.3
DEFAULT_COOPERATE = 0.4
DEFAULT_DOMINATE = 0.2
DEFAULT_ESCAPE = 0.1

# Intent drift
DEFAULT_DRIFT_RATE = 0.01

# Event effects on intent
FOOD_SHORTAGE_SURVIVE_INCREASE = 0.2
FOOD_SHORTAGE_COOPERATE_DECREASE = 0.1
CONFLICT_DOMINATE_INCREASE = 0.15
CONFLICT_SURVIVE_INCREASE = 0.1
CONFLICT_COOPERATE_DECREASE = 0.2
AID_COOPERATE_INCREASE = 0.15
AID_SURVIVE_DECREASE = 0.1
EXTREME_SCARCITY_ESCAPE_INCREASE = 0.25
EXTREME_SCARCITY_SURVIVE_INCREASE = 0.2
DISCOVERY_EXPLORE_INCREASE = 0.2
STABILITY_COOPERATE_INCREASE = 0.1
STABILITY_EXPLORE_INCREASE = 0.1
STABILITY_ESCAPE_DECREASE = 0.1

# Tension effects on intent
ECONOMIC_TENSION_SURVIVE_INCREASE = 0.1
ECONOMIC_TENSION_ESCAPE_INCREASE = 0.15
ECONOMIC_TENSION_THRESHOLD = 0.5
ECONOMIC_TENSION_HIGH_THRESHOLD = 0.7
SOCIAL_TENSION_DOMINATE_INCREASE = 0.1
SOCIAL_TENSION_COOPERATE_DECREASE = 0.1
SOCIAL_TENSION_ESCAPE_INCREASE = 0.1
SOCIAL_TENSION_THRESHOLD = 0.5
SOCIAL_TENSION_HIGH_THRESHOLD = 0.7
POLITICAL_TENSION_DOMINATE_INCREASE = 0.15
POLITICAL_TENSION_ESCAPE_INCREASE = 0.1
POLITICAL_TENSION_THRESHOLD = 0.5
POLITICAL_TENSION_HIGH_THRESHOLD = 0.7
EXISTENTIAL_TENSION_ESCAPE_INCREASE = 0.2
EXISTENTIAL_TENSION_EXPLORE_INCREASE = 0.1
EXISTENTIAL_TENSION_THRESHOLD = 0.5

# Pressure effects on intent
FOOD_PRESSURE_SURVIVE_INCREASE = 0.15
FOOD_PRESSURE_THRESHOLD = 0.6
SCARCITY_ESCAPE_INCREASE = 0.1
WEATHER_BAD_SURVIVE_INCREASE = 0.1
WEATHER_BAD_EXPLORE_DECREASE = 0.05
