"""Constants for memory system."""

# EpisodicMemory defaults
DEFAULT_MAX_EPISODES = 1000
DEFAULT_RECENT_EPISODES = 10

# EmotionalMemory defaults
DEFAULT_MAX_TRACES = 200
DEFAULT_DECAY_RATE = 0.005  # Per turn decay
DEFAULT_EMOTIONAL_TRACE_DECAY_RATE = 0.01
DEFAULT_EMOTION_SUMMARY_LIMIT = 50

# LearnedRulesSystem defaults
DEFAULT_MAX_RULES = 100
DEFAULT_INITIAL_CONFIDENCE = 0.3
DEFAULT_CONFIDENCE_INCREASE = 0.01
DEFAULT_CONFIDENCE_DECREASE = 0.02
DEFAULT_MIN_CONFIDENCE = 0.1
DEFAULT_RULE_CLEANUP_AGE = 1000

# SemanticGraph defaults
DEFAULT_TOKEN_WEIGHT = 1.0
DEFAULT_EDGE_WEIGHT = 1.0
DEFAULT_TOP_K_NEIGHBORS = 10
DEFAULT_CLUSTER_DEPTH = 2
DEFAULT_CLUSTER_TOP_K = 20
