"""Constants for relationships system."""

# RelationshipData defaults
DEFAULT_TRUST = 0.5
DEFAULT_CONFLICT = 0.0
DEFAULT_DEPENDENCY = 0.0

# RelationshipData initialization ranges
INITIAL_TRUST_MIN = 0.3
INITIAL_TRUST_MAX = 0.7
INITIAL_CONFLICT_MIN = 0.0
INITIAL_CONFLICT_MAX = 0.2
INITIAL_DEPENDENCY_MIN = 0.0
INITIAL_DEPENDENCY_MAX = 0.3

# RelationshipGraph defaults
DEFAULT_DRIFT_RATE = 0.001  # Per turn drift

# RelationshipData evolution rates
EVOLUTION_COOPERATION_TRUST_INCREASE = 0.1
EVOLUTION_COOPERATION_DEPENDENCY_INCREASE = 0.05
EVOLUTION_COOPERATION_CONFLICT_DECREASE = 0.05
EVOLUTION_CONFLICT_CONFLICT_INCREASE = 0.2
EVOLUTION_CONFLICT_TRUST_DECREASE = 0.15
EVOLUTION_CONFLICT_DEPENDENCY_DECREASE = 0.1
EVOLUTION_TRADE_TRUST_INCREASE = 0.05
EVOLUTION_TRADE_DEPENDENCY_INCREASE = 0.1
EVOLUTION_RUMOR_TRUST_DECREASE = 0.05
EVOLUTION_RUMOR_CONFLICT_INCREASE = 0.05

# RelationshipData drift rates
DRIFT_TRUST_RATE = 0.5
DRIFT_DEPENDENCY_RATE = 0.3
DRIFT_CONFLICT_RATE = 0.2

# RelationshipGraph thresholds
MIN_TRUST_FOR_ALLIES = 0.6
MAX_CONFLICT_FOR_ALLIES = 0.3
MIN_CONFLICT_FOR_ENEMIES = 0.5
MIN_DEPENDENCY_FOR_DEPENDENTS = 0.4
MIN_TRUST_FOR_COOPERATION = 0.5
MAX_CONFLICT_FOR_COOPERATION = 0.3
MIN_CONFLICT_FOR_CONFLICT = 0.6
MIN_TRUST_FOR_CONFLICT = 0.3
MAX_CONFLICT_FOR_CONFLICT = 0.3
