"""Constants for enhanced relationships system."""

# RelationshipSystem defaults
DEFAULT_DECAY_RATE = 0.001  # Relationship decay per turn without interaction
DEFAULT_FAMILIARITY_GAIN = 0.05  # Familiarity gain per interaction
DEFAULT_INITIAL_TRUST = 0.3  # Start with low trust

# Relationship update rates
COOPERATION_AFFECTION_INCREASE = 0.1
COOPERATION_TRUST_INCREASE = 0.15
COOPERATION_AFFECTION_DECREASE = 0.05
COOPERATION_TRUST_DECREASE = 0.1
CONFLICT_AFFECTION_DECREASE = 0.2
CONFLICT_TRUST_DECREASE = 0.3
TRADE_AFFECTION_INCREASE = 0.05
TRADE_TRUST_INCREASE = 0.1
TRADE_AFFECTION_DECREASE = 0.1
TRADE_TRUST_DECREASE = 0.15
SOCIALIZE_AFFECTION_INCREASE = 0.05
SOCIALIZE_TRUST_INCREASE = 0.05
WORK_AFFECTION_INCREASE = 0.02
WORK_TRUST_INCREASE = 0.03

# Conflict likelihood thresholds
CONFLICT_LIKELIHOOD_MULTIPLIER = 0.1
