"""Constants for tension system."""

# Tension defaults
DEFAULT_ECONOMIC_TENSION = 0.0
DEFAULT_SOCIAL_TENSION = 0.0
DEFAULT_POLITICAL_TENSION = 0.0
DEFAULT_EXISTENTIAL_TENSION = 0.0

# Tension normalization
TENSION_NORMALIZATION_DIVISOR = 100.0

# Tension decay
DEFAULT_TENSION_DECAY_RATE = 0.02  # Per turn decay

# Tension update factors
FOOD_SHORTAGE_ECONOMIC_INCREASE = 0.3
FOOD_SHORTAGE_SOCIAL_INCREASE = 0.2
UNEMPLOYMENT_ECONOMIC_INCREASE = 0.25
UNEMPLOYMENT_SOCIAL_INCREASE = 0.15
CONFLICT_SOCIAL_INCREASE = 0.4
CONFLICT_POLITICAL_INCREASE = 0.3
INEQUALITY_SOCIAL_INCREASE = 0.2
INEQUALITY_POLITICAL_INCREASE = 0.15
AID_ECONOMIC_DECREASE = 0.2
AID_SOCIAL_DECREASE = 0.15
TRADE_SUCCESS_ECONOMIC_DECREASE = 0.15
TRADE_SUCCESS_SOCIAL_DECREASE = 0.1
STABILITY_ALL_DECREASE = 0.1
DISASTER_EXISTENTIAL_INCREASE = 0.3
DISASTER_ECONOMIC_INCREASE = 0.25

# Tension thresholds
HIGH_TENSION_THRESHOLD = 70.0
CRITICAL_TENSION_THRESHOLD = 85.0
