"""World system constants."""

# World state defaults
DEFAULT_SEED = 42
DEFAULT_TURN = 0
DEFAULT_WORLD_STATE = "alive"

# Drives defaults
DEFAULT_STABILITY = 0.5
DEFAULT_NOVELTY = 0.5
DEFAULT_COHESION = 0.5
DEFAULT_EXPRESSION = 0.5

# Drives normalization
DRIVE_MIN = 0.0
DRIVE_MAX = 1.0

# Homeostasis
HOMEOSTASIS_RATE = 0.02
DRIVE_MIDPOINT = 0.5

# Drive update constants
MAX_DRIVE_DELTA = 0.05
STABILITY_COHERENCE_FACTOR = 0.1
STABILITY_NOVELTY_FACTOR = 0.1
STABILITY_INTERACTION_FACTOR = 0.05
NOVELTY_DIVERSITY_FACTOR = 0.1
NOVELTY_STABILITY_FACTOR = 0.05
COHESION_COHERENCE_FACTOR = 0.1
COHESION_STIMULUS_FACTOR = 0.02
COHESION_STIMULUS_DIVISOR = 10.0
EXPRESSION_INTERACTION_FACTOR = 0.1
EXPRESSION_STABILITY_FACTOR = 0.05

# Drive coupling thresholds
COUPLING_STABILITY_THRESHOLD = 0.85
COUPLING_NOVELTY_THRESHOLD = 0.15
COUPLING_NOVELTY_BOOST = 0.05
COUPLING_EXPRESSION_BOOST = 0.03
COUPLING_COHERENCE_THRESHOLD = 0.90
COUPLING_DIVERSITY_THRESHOLD = 0.20
COUPLING_COHESION_REDUCTION = 0.04

# Population pressure constants
POPULATION_PRESSURE_REPRODUCTION_FACTOR = 0.1
EXTINCTION_RISK_THRESHOLD = 0.6
EXTINCTION_RISK_SURVIVAL_BOOST = 0.05

# Generational trauma
TRAUMA_TRACKING_TURNS = 50

# Civilization phases
CIVILIZATION_PHASE_SURVIVAL = "survival"
CIVILIZATION_PHASE_GROWTH = "growth"
CIVILIZATION_PHASE_STABLE = "stable"
CIVILIZATION_PHASE_STRAIN = "strain"
CIVILIZATION_PHASE_DECLINE = "decline"

# Civilization phase thresholds
PHASE_SURVIVAL_ACTIVE_AGENTS_THRESHOLD = 20
PHASE_SURVIVAL_EXTINCTION_RISK_THRESHOLD = 0.7
PHASE_DECLINE_POPULATION_PRESSURE_THRESHOLD = 0.8
PHASE_DECLINE_EXTINCTION_RISK_THRESHOLD = 0.5
PHASE_STRAIN_PRESSURE_THRESHOLD = 0.7
PHASE_STRAIN_TOTAL_POPULATION_THRESHOLD = 5000
PHASE_STRAIN_POPULATION_PRESSURE_THRESHOLD = 0.6
PHASE_GROWTH_CHILD_POOL_RATIO = 0.5
PHASE_GROWTH_POPULATION_PRESSURE_THRESHOLD = 0.4
PHASE_GROWTH_EXTINCTION_RISK_THRESHOLD = 0.3
