"""Constants for world flags system."""

# Flag condition thresholds
KORA_FAMINE_FOOD_THRESHOLD = 10
RIFT_UNREST_TENSION_THRESHOLD = 80
LUME_ECONOMIC_COLLAPSE_CREDITS_THRESHOLD = 20
LUME_ECONOMIC_COLLAPSE_JOBS_THRESHOLD = 2
ZEPH_DOMINANCE_FOOD_THRESHOLD = 80
ZEPH_DOMINANCE_TENSION_THRESHOLD = 30
POPULATION_DECLINE_FOOD_THRESHOLD = 20
TRADE_COLLAPSE_CREDITS_THRESHOLD = 20
TRADE_COLLAPSE_DISTRICT_COUNT = 3

# Flag effects - Kora Famine
KORA_FAMINE_FOOD_NEED_MULTIPLIER = 1.5
KORA_FAMINE_MIGRATION_RATE = 0.3
KORA_FAMINE_TENSION_BASE = 20.0
KORA_FAMINE_REPRODUCTION_REDUCTION = 0.7
KORA_FAMINE_RELATIONSHIP_DECAY_MULTIPLIER = 1.5
KORA_FAMINE_CONFLICT_MULTIPLIER = 1.4
KORA_FAMINE_FOOD_SHORTAGE_MODIFIER = 1.5
KORA_FAMINE_CONFLICT_MODIFIER = 1.3

# Flag effects - Rift Unrest
RIFT_UNREST_CONFLICT_PROBABILITY = 1.4
RIFT_UNREST_COOPERATION_REDUCTION = 0.2
RIFT_UNREST_TENSION_DECAY_REDUCTION = 0.3
RIFT_UNREST_TRUST_FORMATION_REDUCTION = 0.5
RIFT_UNREST_REPRODUCTION_REDUCTION = 0.6
RIFT_UNREST_RIOT_MODIFIER = 1.5
RIFT_UNREST_STRIKE_MODIFIER = 1.3

# Flag effects - Lume Economic Collapse
LUME_COLLAPSE_JOB_AVAILABILITY_MULTIPLIER = 0.5
LUME_COLLAPSE_TRADE_SUCCESS_REDUCTION = 0.4
LUME_COLLAPSE_CREDITS_LOSS_RATE = 1.3
LUME_COLLAPSE_UNEMPLOYMENT_MODIFIER = 1.6
LUME_COLLAPSE_MIGRATION_MODIFIER = 1.4

# Flag effects - Zeph Dominance
ZEPH_DOMINANCE_RESOURCE_ATTRACTION = 0.2
ZEPH_DOMINANCE_MIGRATION_INFLOW = 0.3
ZEPH_DOMINANCE_COOPERATION_BONUS = 0.15
ZEPH_DOMINANCE_AID_MODIFIER = 1.3
ZEPH_DOMINANCE_TRADE_SUCCESS_MODIFIER = 1.2

# Flag effects - Population Decline
POPULATION_DECLINE_REPRODUCTION_REDUCTION = 0.5
POPULATION_DECLINE_MIGRATION_RATE = 0.2
POPULATION_DECLINE_RELATIONSHIP_DECAY_MULTIPLIER = 1.3
POPULATION_DECLINE_DEATH_MODIFIER = 1.2

# Flag effects - Trade Collapse
TRADE_COLLAPSE_TRADE_SUCCESS_REDUCTION = 0.8
TRADE_COLLAPSE_TENSION_BASE = 15.0
TRADE_COLLAPSE_TRUST_FORMATION_REDUCTION = 0.4
TRADE_COLLAPSE_COOPERATION_REDUCTION = 0.3
TRADE_COLLAPSE_CONFLICT_MODIFIER = 1.4
TRADE_COLLAPSE_THEFT_MODIFIER = 1.5
